services:
  - type: web
    name: imgproc-go
    env: docker
    dockerfilePath: ./webfilter/Dockerfile
    dockerContext: ./webfilter
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8080
